name: my_product_app
description: Um aplicativo simples para gerenciamento de produtos com persistência local.

publish_to: 'none' # Impede a publicação acidental no pub.dev

version: 1.0.0+1

environment:
  # Garante que está usando uma versão recente do Dart
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # A dependência chave para o armazenamento local no navegador
  shared_preferences: ^2.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true